# Generated by Django 2.2.3 on 2019-07-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
